spring:
  application:
    name: socketbroker
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
caas:
  endpoint: ${BROKER_ENDPOINT}
  conport:
    server:
      port: 4001
    redis:
      db: 0
  consumer:
    server:
      port: 6006
  hub:
    server:
      url: https://hub.p2pcaas.60jong.dev
