spring:
  application:
    name: socketbroker
  data:
    redis:
      host: localhost
      port: 6379
caas:
  endpoint: ${BROKER_ENDPOINT}
  conport:
    server:
      port: 4001
    redis:
      db: 0
  consumer:
    server:
      port: 6006
  hub:
    server:
      url: http://localhost:8080
