spring:
  application:
    name: cass.relay
  data:
    redis:
      host: localhost
      port: 6379
caas:
  agent:
    server:
      port: 4001
    redis:
      db: 0
  relay:
    server:
      port: 6006
